auto: true
server: true
permalink: /docs/:categories/:title
pygments: true
gauges_id: 503c5af6613f5d0f19000027

# Sass Configuration
sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed

# Jekyll Models
jekyll_models: [projects, tests]
jekyll_models_urls: rest-like
site_base: http://localhost:4000/
